### ISSUE TITLE
Allow saving traces to a file

### ISSUE THREAD

**Issue by SimonBrandner** [nagisa/rust_tracy_client#116]
Tracy allows loading traces from a file, it would be super useful to allow `tracing-tracy` to save traces into files. This is quite useful if one wants to use traces attached to bug reports for example

![image](https://cdn.discordapp.com/attachments/627649734592561152/1277967485047668756/image.png?ex=66cf1777&is=66cdc5f7&hm=311721f0d143f460a3a7b673e6596db2aefa9cb500e0a8dc97023941763cb3c6&)

(in the case this is already implemented, I did not manage to find it in the docs)

**Comment by nagisa** [comment]
You use tracy's own tooling to record traces to a file. In particular `capture`. Would be surprised if tracy's manual didn't have any text on it (but also have no time to check right now.)

**Comment by SimonBrandner** [comment]
I am not sure we understand each other... I would like to have the ability to save the trace to a file after my app finishes running. This is super useful if a user sees a bug - they can then attach the trace file to a bug report. I am not sure how tracy's tooling would help here... What am I missing?

**Comment by Ralith** [comment]
It sounds like the only supported way to create those files is with tracy itself. Unless you can identify an API for doing so when tracy isn't attached?

**Comment by SimonBrandner** [comment]
Well, I was asking for that API. (that is if I understand what you mean)

**Comment by Ralith** [comment]
This project is an FFI binding. Major feature requests should be taken upstream.

**Comment by SimonBrandner** [comment]
Ah, ok, makes sense

**Comment by SimonBrandner** [comment]
(sorry for the trouble here)

**Comment by nagisa** [comment]
> I would like to have the ability to save the trace to a file after my app finishes running. This is super useful if a user sees a bug - they can then attach the trace file to a bug report. I am not sure how tracy's tooling would help here... What am I missing?

This is exactly what the `capture` tool from the upstream project will give you – a file on the filesystem containing a trace of your app. You might consider spawning this tool from within your program (cf. `std::process::...`) if it makes sense in your application but that does have some significant considerations with regards to the amount of data stored/written on the user's machine.

**Comment by SimonBrandner** [comment]
Thank you for the pointer!
