### ISSUE TITLE
Vulkan profiling

### ISSUE THREAD

**Issue by Ralith** [nagisa/rust_tracy_client#19]
Tracy supports profiling of GPU-side work under Vulkan. It doesn't look like that's exposed yet.

**Comment by nagisa** [comment]
I don't believe there's a C API for this functionality. Or the related OpenGL, DXD11, DXD12 and OpenCL APIs, for that matter.

We can wrap the C++ APIs ourselves, of course, but ideally upstream provided these.

**Comment by Ralith** [comment]
Upstream issue at https://github.com/wolfpld/tracy/issues/180.

**Comment by temportalflux** [comment]
Bumping this ticket from the summer - looks like the bare-bones C API for graphics profiling was merged in last month? Is there anything else blocking this ticket?

**Comment by farnoy** [comment]
I think this can be closed, the C API has been exposed for a long while now.

**Comment by nagisa** [comment]
Thanks, yeah. There're also APIs at a higher level in tracy-client as well. Any follow up work should be tracked in new issues.
