### ISSUE TITLE
Make TracyCZoneCtx Send

### ISSUE THREAD

**Issue by hardliner66** [nagisa/rust_tracy_client#2]
Would it be possible to make TracyCZoneCtx `Send`?

Currently I'm trying to use a tracy span inside an async function, but the compiler tells me the function cannot be spawned because TracyCZoneCtx isn't `Send`.

```
error: future cannot be sent between threads safely
  --> src\kernel\kernel_ref.rs:45:14
   |
45 |             .spawn(async move {
   |              ^^^^^ future created by async block is not `Send`
   |
   = help: within `impl core::future::future::Future`, the trait `std::marker::Send` is not implemented for `*mut tracy_client_sys::TracyCZoneCtx`
note: future is not `Send` as this value is used across an await
```

**Comment by nagisa** [comment]
Tracy itself requires the two ends of a span to not cross thread boundaries, otherwise you’ll get an error message about incorrectly instrumented application.

**Comment by nagisa** [comment]
I’m going to close this as inactionable.

**Comment by hardliner66** [comment]
That makes sense, thanks for clarifying.

**Comment by clarkmcc** [comment]
Does this mean that it's not possible to instrument an async function, or is there a workaround?

**Comment by nagisa** [comment]
You could use a single-threaded runtime to drop the `Send` requirement. Or you could create a new span, enter and exit it for each `Future::poll`, rather than having span remain entered throughout the future lifetime.
