### ISSUE TITLE
Change the client port

### ISSUE THREAD

**Issue by kbleeke** [nagisa/rust_tracy_client#22]
Hi

Is is possible to change the client port that the server connects to?

For Context:
I am testing a replicated system on localhost. I have multiple instances of the same binary. The tracy cli seems to select one of them at random to capture the profile. I would like to choose one replica myself instead by having all of them listen on different ports.

My understanding is that by including this crate is it automatically enabled at compile time. It would be kind of inconvenient to produce different binaries.

I had a brief look at all three crates but I couldn't find an exposed setting. Happy to submit a PR with some guidance.

Thanks

**Comment by nagisa** [comment]
Yeah, as far as I know there is no way to change the port besides the environment variable, and I don't believe the client libraries will add an API to do so in the future.
