### ISSUE TITLE
__tracy_gpu_new_context_data has private field making it unconstructable

### ISSUE THREAD

**Issue by cwfitzgerald** [nagisa/rust_tracy_client#39]
Oddly it seems to have a completely private field which we need to fill to be able to call the function. I'm not sure what caused bindgen to emit this one field as private.

https://docs.rs/tracy-client-sys/latest/tracy_client_sys/struct.___tracy_gpu_new_context_data.html

**Comment by Imberflur** [comment]
It seems to be cause by this line https://github.com/nagisa/rust_tracy_client/blob/03bd339c0a05cc3797e085e63fde8d075b9ee8be/make_sys.sh#L37 which I think (looking at `generated.rs`) is for removing `pub` from generated type aliases.

**Comment by Imberflur** [comment]
A simple fix might be to switch to:
```
 sed -i 's/pub type /type /g' 'tracy-client-sys/src/generated.rs'
```

**Comment by nagisa** [comment]
Yeah, the sed post-processing here is to avoid re-exporting 

```
type __uint8_t = ::std::os::raw::c_uchar;
```

and similar. Happy to take a patch here.
