### ISSUE TITLE
Crash with long messages

### ISSUE THREAD

**Issue by Imberflur** [nagisa/rust_tracy_client#4]
```
veloren-voxygen: tracy/client/TracyProfiler.cpp:2186: void tracy::Profiler::SendString(uint64_t, const char*, tracy::QueueType): Assertion `len <= std::numeric_limits<uint16_t>::max()' failed.
Aborted (core dumped)
```

When I removed all filtering I got this crash.
I assume one of my deps is producing TRACE level events with a long message.

**Comment by nagisa** [comment]
Huh, I guess there's a limitation like that. There's a release 0.7.1 of Tracy that I will look to upgrade this library to shortly, so lets see if that maybe fixes the issue (however unlikely it may be). If not, lets look into reporting this to upstream while also introducing a workaround here.

It’ll likely involve truncating the message, sadly. 65kB of message data does seem like somewhat excessive and expensive for an event.

**Comment by nagisa** [comment]
Filled an issue upstream https://github.com/wolfpld/tracy/issues/100

But honestly speaking you may want to track down where this large string is being produced and ignore the fields or something. I had something similar happen in my codebase with `#[instrument]` macro where I would format a huge matrix from an argument. It slowed down things significantly enough that not only the profiling/tracing results were no longer accurate but the program became outright unusable at that point.

**Comment by Imberflur** [comment]
I was able to fix it by introducing a bit of filtering on some of the dependencies being used. However, I was wondering if `tracy-client` should try to catch strings that are too long for tracy to handle and truncate them.

**Comment by nagisa** [comment]
yep, it probably should.
