### ISSUE TITLE
Documentation on the available feature flags is not-trivial to discover

### ISSUE THREAD

**Issue by semirix** [nagisa/rust_tracy_client#46]
I have a remote server I'd like to profile more than once, however if I disconnect, it says:

```
The client you are trying to connect to is no longer able to send 
profiling data, because another server was already connected to it.
You can do the following:

1. Restart the client application.
2. Rebuild the client application with on-demand mode enabled.
```

Is there a way to enable on-demand mode?

**Comment by nagisa** [comment]
Did you try the ondemand crate feature?

**Comment by semirix** [comment]
I wasn't aware there was a crate feature for this. It seems to work now, thank you. Additionally, it would be nice if there was clearer documentation for it. I didn't see anything in the readme or the docs.

**Comment by nagisa** [comment]
The features are documented in the [`sys`](https://docs.rs/tracy-client-sys/latest/tracy_client_sys/#features) crate, and this section is linked from the [other](https://docs.rs/tracy-client/latest/tracy_client/#features) (crates )[https://docs.rs/tracing-tracy/latest/tracing_tracy/#features), but I guess I see your point that it isn’t necessarily super apparent that you’d want to look for the crate features in the first place when presented with such a message.

Too bad it isn’t super straightforward to share documentation between crates…
