### ISSUE TITLE
tracy-client-sys 0.18.0 is not on crates.io

### ISSUE THREAD

**Issue by NickNick** [nagisa/rust_tracy_client#50]
I don't think this crate has been published. Is that on purpose? I got an incompatible message when trying to attach from 0.8.2.

Worked around it by specifying this git repository directly as dependency: `tracing-tracy = { git = "https://github.com/nagisa/rust_tracy_client.git" }`

**Comment by nagisa** [comment]
Aha, my bad! Published!
