### ISSUE TITLE
tracy-client 0.14.1 is not on crates.io

### ISSUE THREAD

**Issue by Latias94** [nagisa/rust_tracy_client#51]
I'm using tracy's newest release version 0.8.2, but `tracy-client` have only 0.14.0 on crate.io, which cause 
"The client you are trying to connect to uses incompatible protocol version.
Make sure you are using the same Tracy version on both client and server."

related issue: https://github.com/aclysma/profiling/pull/38#issuecomment-1253026999

For now, i'm using `tracy-client =  { git = "https://github.com/nagisa/rust_tracy_client.git", version = "0.14.1"}` for a temporary solution.
Moreover, is there a way to specific the `tracy-client-sys` version of `tracy-client` crate in Cargo.toml?

**Comment by nagisa** [comment]
Ah, my bad! I should’ve taken a closer look when I was working on https://github.com/nagisa/rust_tracy_client/issues/50!

I should really automate this all away ://
