### ISSUE TITLE
Will not build for --target x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by John-Nagle** [nagisa/rust_tracy_client#62]
Won't build for --target x86_64-pc-windows-gnu due to a C++ compile error involving `#include <mutex>`.  C++ type **std::mutex** was apparently moved out of "std" and into "mutex" in the C++ standard library used by **x86_64-pc-windows-gnu** and now there's a versioning problem.

Compile error:
```
warning: In file included from tracy/client/TracyProfiler.hpp:18,
warning:                  from tracy/client/TracyScoped.hpp:11,
warning:                  from tracy/client/TracyProfiler.cpp:69,
warning:                  from tracy/TracyClient.cpp:23:
warning: tracy/client/../common/TracyMutex.hpp:19:25: error: ‘mutex’ in namespace ‘std’ does not name a type
warning:    19 | using TracyMutex = std::mutex;
warning:       |                         ^~~~~
warning: tracy/client/../common/TracyMutex.hpp:16:1: note: ‘std::mutex’ is defined in header ‘<mutex>’; did you forget to ‘#include <mutex>’?
warning:    15 | #include <mutex>
warning:   +++ |+#include <mutex>
warning:    16 | 
```

Reproduce by
```
https://github.com/John-Nagle/ui-mock.git
cd ui-mock
cargo build --features tracy --examples --target x86_64-pc-windows-gnu
```
Run under Ubuntu 20.04.2 LTS.

Stable rustc: rustc 1.69.0 (84c898d65 2023-04-16)

**Comment by nagisa** [comment]
Oh, sorry. By upstream I meant https://github.com/wolfpld/tracy. All of the `tracy-client{,-sys}` and `tracing-tracy` are part of this project.

**Comment by John-Nagle** [comment]
The funny thing is, this worked for a while last year. See https://github.com/nagisa/rust_tracy_client/issues/31

In


Where does the C++ in 

This is some kind of version incompatibility problem. I'm looking through C++11 / C++17 etc differences to see if the location of "mutex" changed. 

I can't build the Tracy profiler on Linux at all. There's a problem with the Capstone library. But I can run the Tracy executable of the profiler under Wine to talk to a running Linux program!

**Comment by John-Nagle** [comment]
Checking versions of everything.

The C++ build command issued by the build.rs script in rust_tracy_client is:

` "x86_64-w64-mingw32-g++" "-O0" "-ffunction-sections" "-fdata-sections" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "-std=c++11" "-DTRACY_ENABLE" "-DTRACY_MANUAL_LIFETIME" "-DTRACY_DELAYED_INIT" "-o" "/home/john/projects/rustcode/rust_tracy_client/target/x86_64-pc-windows-gnu/debug/build/tracy-client-sys-321ed9b25eb951d3/out/tracy/TracyClient.o" "-c" "tracy/TracyClient.cpp"
`
Notes: 

- "std=c++11" is set. That matches what build.rs wants to set. Looking at Tracy, it appears that Tracy is supposed to be compiled for C++11, not C++14, 17, or later. So that appears to be correct.
- "x86_64-w604-mingw32-g++" targets 32-bit Windows. **Why is that being run?** This is an all 64 bit project. There is an all 64 bit version of the compiler available.
- On my system, the current versions of all the mingw tools are "10.3.0.14ubuntu24.3". [That appears to be current.](https://www.mingw-w64.org/downloads/)

**Comment by John-Nagle** [comment]
This seems to be related to building for POSIX threads vs Windows threads. See:

https://9to5answer.com/c-mutex-in-namespace-std-does-not-name-a-type

Not yet sure what the correct settings are, but that's the problem area.

**Comment by John-Nagle** [comment]
I looked at building the upstream C++ package from Tracy. But that's built with makefiles, and, apparently, Clang.
 I don't know if they've ever tried mingw cross-compilation. There's no obvious way to make their build system do that.

rust_tracy_client is built with what "cc::Build" picks. That leads to the "mutex" problem. I tried forcing a compile with "x86_64-w64-mingw32-g++-posix" by modifying "build.rs". That fixes the mutex problem but introduces other errors:

```
running: "x86_64-w64-mingw32-g++-posix" "-O0" "-ffunction-sections" "-fdata-sections" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "-std=c++11" "-DTRACY_ENABLE" "-DTRACY_MANUAL_LIFETIME" "-DTRACY_DELAYED_INIT" "-o" "/home/john/projects/rustcode/rust_tracy_client/target/x86_64-pc-windows-gnu/debug/build/tracy-client-sys-321ed9b25eb951d3/out/tracy/TracyClient.o" "-c" "tracy/TracyClient.cpp"
  cargo:warning=In file included from tracy/TracyClient.cpp:26:
  cargo:warning=tracy/client/TracySysTrace.cpp: In function ‘bool tracy::SysTraceStart(int64_t&)’:
  cargo:warning=tracy/client/TracySysTrace.cpp:360:37: error: ‘TraceSetInformation’ was not declared in this scope; did you mean ‘HeapSetInformation’?
  cargo:warning=  360 |         const auto intervalStatus = TraceSetInformation( 0, TraceSampledProfileIntervalInfo, &interval, sizeof( interval ) );
  cargo:warning=      |                                     ^~~~~~~~~~~~~~~~~~~
  cargo:warning=      |                                     HeapSetInformation
```
Those functions all operate on Windows threads. 

There does seem to be support for Mingw in Tracys client. There are references to `defined(__MINGW32__)`
.
When Rust is running on Windows, is it using POSIX threads or Windows threads?

**Comment by nagisa** [comment]
Triage: closing as there aren't obvious indications this is a fault in this project.
