### ISSUE TITLE
Errors resolving call stack

### ISSUE THREAD

**Issue by adaszko** [nagisa/rust_tracy_client#67]
Hi 👋 

I'm trying to use this great crate on an aarch64 macOS and running into some errors:

<img width="1747" alt="image" src="https://github.com/nagisa/rust_tracy_client/assets/165678/464640d3-b4d7-41d0-8e35-6dbe313ca789">

<img width="1759" alt="image" src="https://github.com/nagisa/rust_tracy_client/assets/165678/be38e118-caa7-47f3-b388-d9cb6b3e873f">

The way I'm emitting this message from my code:
```Rust
tracy_client::Client::running().unwrap().message("foo", 10);
```

Any ideas as to what might be going wrong?  Thank you in advance!

**Comment by nagisa** [comment]
Unfortunately I can’t really help with what seem to be issues outside of these bindings themselves. One guess I have is that this was compiled in a release mode and the underlying `Tracy` library is unable to get stacktraces in this configuration… I’d be curious to know if you managed to figure it out, but unless shown that this is an issue in these bindings I will have to close this issue for the time being.
