### ISSUE TITLE
Garbage characters when using tracing

### ISSUE THREAD

**Issue by mamcx** [nagisa/rust_tracy_client#72]
The `tracy` client show garbage characters in the output.

When I instrument code like 

```rust
    #[tracing::instrument(skip(self, tx))]
    pub fn iter<'a>(&'a self, tx: &'a MutTxId, table_id: u32) -> Result<Iter<'a>, DBError> {
```

the `table_id: u32` parameter is joined as zone:

```
iter{[3mtable_id[0m[2m=[0m1}
```

I expect it to be 

```
iter (table_id:1)
```

or similar.

**Comment by Ralith** [comment]
Those look like ANSI escape codes. Perhaps something's trying to pretty-print that information for display in a terminal?

**Comment by mamcx** [comment]
Yes, they are. But how disable them for `tracy`?

We have the [config here](https://github.com/clockworklabs/SpacetimeDB/blob/cb42225d0a250b378b56f0a31cb4808292b6a1aa/crates/core/src/startup.rs#L12).

But we don't want to disable it globally:

```rust
    let fmt_layer = tracing_subscriber::fmt::Layer::default()
        .with_writer(write_to)
        .event_format(format)
        .with_ansi(false); <-- Need only for tracy

    let env_filter_layer = parse_from_file(&conf_file);

    let tracy_layer = if std::env::var("SPACETIMEDB_TRACY").is_ok() {
        Some(tracing_tracy::TracyLayer::new())
    } else {
        None
    };

    let subscriber = tracing_subscriber::Registry::default()
        .with(fmt_layer)
        .with(tracy_layer)
        .with(flame_layer);
```

**Comment by mamcx** [comment]
Oh, just reordering the layers works:


```rust
    let subscriber = tracing_subscriber::Registry::default()
        .with(tracy_layer)
        .with(fmt_layer)
        .with(flame_layer);
```

**Comment by nagisa** [comment]
Does it truly? I would expect that doing so should change the output of the stdout logs? The truly correct thing to do would be to provide a [different type (even if just a newtype) for formatter](https://docs.rs/tracing-tracy/latest/tracing_tracy/struct.TracyLayer.html#method.with_formatter). That way `tracing-tracy` will not attempt to re-use a formatted event/span representation from the other layer(s).
