### ISSUE TITLE
TRACY_NO_EXIT doesn't do anything

### ISSUE THREAD

**Issue by SUPERCILEX** [nagisa/rust_tracy_client#79]
Not sure if this has anything to do with the rust side of things, but I thought it was supposed to block my binary from exiting. Is there some API I need to call to make this happen when using tokio tracing? Also there should probably be a feature tied to this envvar.

**Comment by nagisa** [comment]
That is most likely a direct outcome of https://github.com/nagisa/rust_tracy_client/issues/78

**Comment by SUPERCILEX** [comment]
Yeah, I'm gonna work on that.
