### ISSUE TITLE
Assertion failed: size < std::numeric_limits<uint16_t>::max()

### ISSUE THREAD

**Issue by fabianbergmark** [nagisa/rust_tracy_client#8]
When registering Tracy with
tracing_subscriber::registry()
        .with(TracyLayer::new().with_stackdepth(0))
        .init();

on startup, my application crashes with
Assertion failed: size < std::numeric_limits<uint16_t>::max(), file ...\tracy-client-sys-0.10.0\tracy\client\TracyProfiler.hpp, line 282
error: process didn't exit successfully: target\release\world.exe (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)

**Comment by nagisa** [comment]
Looks like a duplicate of https://github.com/nagisa/rust_tracy_client/issues/4 – you have an event somewhere that's very long.

**Comment by nagisa** [comment]
This should be fixed now.
