### ISSUE TITLE
Debug symbols don't show up in trace

### ISSUE THREAD

**Issue by SUPERCILEX** [nagisa/rust_tracy_client#80]
I'm not sure if I'm not doing something I should be, but I only get addresses in my profile.

**Comment by nagisa** [comment]
It might be because the stack collection defaults to 0 frames for overhead reasons. You can specify a depth you want to use through various APIs, such as `TracyLayer::with_stackdepth` or the 2nd argument of the `tracy_client::span!` macro.

**Comment by SUPERCILEX** [comment]
Nope, sadly that didn't fix it. I asked in the tracy discord so we'll see what happens there. Otherwise I'll ask the bevy folks since they're probably the biggest users of this crate.

**Comment by SUPERCILEX** [comment]
Ok, this is also caused by not calling shutdown. I got symbols to show up by disabling the manual-lifetimes feature.
