### ISSUE TITLE
Support for Protocol V65.

### ISSUE THREAD

**Issue by codecnotsupported** [nagisa/rust_tracy_client#93]
Current support is 64.
Relevant commit.
https://github.com/wolfpld/tracy/commit/41fc2930434bb2296cc8c255f82bcb731f8c0f06#diff-5879b3a569179bb49a8dc1064f461680a142313c3cc6358cbe9445d7f7b28605L9

**Comment by nagisa** [comment]
This project closely follows upstream releases, and I don't see me making a change to said policy. You might have better success requesting upstream to make a release on their end.
