### ISSUE TITLE
Frame images

### ISSUE THREAD

**Issue by colinmarc** [nagisa/rust_tracy_client#96]
The PDF mentions an API (`FrameImage`) for sending screengrabs to the server. Is that something that's possible to support in the rust client?

> It is possible to attach a screen capture of your application to any frame in the main frame set. This can help
you see the context of what’s happening in various places in the trace. You need to implement retrieval of
the image data from GPU by yourself.
Images are sent using the FrameImage(image, width, height, offset, flip) macro, where image is
a pointer to RGBA32 pixel data, width and height are the image dimensions, which must be divisible by 4,
offset specifies how much frame lag was there for the current image (see chapter 3.3.3.1), and flip should
be set, if the graphics API stores images upside-down33. The profiler copies the image data, so you don’t
need to retain it

Thanks in advance!

**Comment by Dinnerbone** [comment]
I think this can be closed now? Added in #97
